version: '3'
services:

  dsw_server:
    image: datastewardshipwizard/wizard-server:2.0.0
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./server/application.yml:/application/engine-wizard/config/application.yml
      - ./server/integration.yml:/application/engine-wizard/config/integration.yml

  dsw_client:
    image: datastewardshipwizard/wizard-client:2.0.0
    restart: always
    ports:
      - 8080:80
    environment:
      - API_URL=http://localhost:3000
    volumes:
      - ./client/extras.scss:/src/scss/customizations/_extras.scss
      - ./client/overrides.scss:/src/scss/customizations/_overrides.scss
      - ./client/variables.scss:/src/scss/customizations/_variables.scss
      - ./client/assets:/usr/share/nginx/html/assets

  mongo:
      image: mongo:4.0.12
      restart: always
      ports:
        - 27017:27017
      # volumes:
      #     - ./mongo/data:/data/db
